---
# Ubuntu18.04
- name: Update the apt package index
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install packages for apt add repository over HTTPs
  become: yes
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  vars:
      packages:
      - git
      - vim